# -*- coding: utf-8 -*-
"""Movie ticket booking sif2500070 deshan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fMeVrHqSdU85uXbnbFsI0sa_fT6H8yZL
"""

print ("Movie Ticket Booking system")
name= input("Enter your name")
mobile=input("Enter your mobile number:")
ticket= input("Enter ticket type (Regular/vip):")
quantity= int(input("Enter number of ticket"))

if ticket=="regular":
   price=500
elif ticket=="vip":
  price=1000
else:
  print("Invalid ticket type")
  exit()

total=price*quantity
if total > 3000:
   discount=total*0.10
else:
   discount=0
final=total-discount

print("Bill")
print("Name:",name)
print("Mobile:",mobile)
print("Total:",total)
print("Discount:",discount)
print("Final Amount:",final )
